[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "psifr-notebooks"
version = "0.1.0"
dependencies = [
    "psifr",
    "jupyterlab",
    "watermark",
]
